import datetime


def contest_data_list():
    data = [{'title': '부산테크노파크',
             'content': '[부산테크노파크] 제4회 치의학 산업 전국 아이디어 경진대회 참가자 모집 (~12/10 까지)  SPECIAL 분야 : 기획/아이디어, 논문/리포트, 웹/모)',
             'date': datetime.date(2023, 12, 9),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=view&gp=1&ix=82715'},
            {'title': '경남국제개발협력센터',
             'content': '경남에 개발협력이 오다(ODA) 카드뉴스 공모전   분야 : 디자인/캐릭터/웹툰',
             'date': datetime.date(2023, 12, 9),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82934'},
            {'title': '동작구',
             'content': '동작구형 특\u200b화아파트 아이디어 공모전   분야 : 기획/아이디어',
             'date': datetime.date(2023, 12, 10),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82955'},
            {'title': '삼성금융네트웍스',
             'content': '2023년 12월 삼성 금융멘토링 교육생 모집  SPECIAL 분야 : 기획/아이디어, 광고/마케팅, 대외활동/서포터즈, 취업/창업, 기타',
             'date': datetime.date(2023,12, 13),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=view&gp=1&ix=82848'},
            {'title': '한국화웨이, HUAWEI, Huawei ICT Academy',
             'content': '한국화웨이 ICT 경진대회 2023-2024 참가자 모집  SPECIAL IDEA분야 : 기획/아이디어, 논문/리포트, 웹/모바일/IT',
             'date':datetime.date(2023, 12, 13),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82714'},
            {'title': '문화체육관광부, 강원특별자치도',
             'content': '2024 강원 동계청소년올림픽대회 개최 기념 그림 공모전  SPECIAL 분야 : 광고/마케팅, 디자인/캐릭터/웹툰, 웹/모바일/IT',
             'date': datetime.date(2023, 12, 14),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=view&gp=1&ix=82717'},
            {'title': '군포시늘푸른노인복지관',
             'content': '군포시늘푸른노인복지관 CI 제작 공모전   분야 : 디자인/캐릭터/웹툰',
             'date': datetime.date(2023, 12, 14),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82952'},
            {'title': '재단법인 천만장학회',
             'content': '2024 제2회 ChunMan Art for Young 공모전 (시각예술 전 분야)  SPECIAL 분야 : 영상/UCC/사진, 웹/모바일/IT, 예체능/미술/음악, 기타',
             'date':datetime.date(2023, 12, 15),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=81310'},
            {'title': '인천일보',
             'content': '인천일보 대학생 서포터즈 1기 모집   분야 : 대외활동/서포터즈',
             'date': datetime.date(2023, 12, 15),
             'link': 'https://www.wevity.com/?c=fin'},
            {'title': '일간스포츠',
             'content': '[CJ/롯데엔터테이먼트] 콘텐츠&미디어 대기업에서 직무스펙 쌓고 서류합격률 200% 올리는 실무활동! (12/17)  SPECIAL 분야 : 기획/아이디어, 광고',
             'date':datetime.date(2023, 12, 16),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82762'},
            {'title': 'NH농협은행',
             'content': 'NH농협은행 대학생봉사단 N돌핀 12기 모집   분야 : 대외활동/서포터즈',
             'date': datetime.date(2023, 12, 19),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82941'},
            {'title': '경북대학교 스타트업지원센터',
             'content': '2023 공공데이터 활용 나드리콜 개선 아이디어 발굴 해커톤 신규 분야 : 기획/아이디어',
             'date': datetime.date(2023, 12, 20),
             'link':"https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82962"},
            {'title': "사단법인 이타서울",
             'content': "쓰레기를 줍고 크리스마스 꾸러미를 기부해요! 나눔플로깅 참여자 모집 분야 : 기타",
             'date': datetime.date(2023, 12, 20),
             'link': "https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82937"},
            {'title': "한양사이버대학교",
             'content':"2023 제 2회 한양사이버대학교 공유가치 콘텐츠 공모전 SPECIAL 분야 : 광고/마케팅, 영상/UCC/사진, 웹/모바일/IT, 예체능/미술/음악, 대외활동/서포터즈",
             'date': datetime.date(2023, 12, 21),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82936'},
            {'title':'에브리세컨드',
             'content':'무인사진관 픽닷(pic dot.) 공식 서포터즈 2기 모집 분야 : 대외활동/서포터즈',
             'date': datetime.date(2023, 12, 21),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82932'},
            {'title':'서울시',
             'content':'2023 서울시 청년정책 숏폼 영상 공모전 분야 : 영상/UCC/사진',
             'date':datetime.date(2023, 12, 24),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82951'},
            {'title':'삼성생명',
             'content':'삼성 Financial Networks 금융연수 프로그램 3기 모집 SPECIAL 분야 : 기획/아이디어, 광고/마케팅, 대외활동/서포터즈, 취업/창업, 기타',
             'date':datetime.date(2023, 12, 26),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82615'},
            {'title':'(주)라사라패션교육개발',
             'content':'2023, 제3회 Fly high! 3D가상 창작 디자인 공모전 분야 : 디자인/캐릭터/웹툰',
             'date':datetime.date(2023, 12, 28),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82953'},
            {'title':'한국원자력협력재단',
             'content':'[한국원자력협력재단] 원자력 아이디어 제안전 (스피치 콘테스트) 분야 : 과학/공학',
             'date':datetime.date(2023, 12, 28),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82943'},
            {'title':'재외동포청워킹홀리데이인포센터',
             'content':'2023 워킹홀리데이 콘텐츠 공모전 신규 분야 : 영상/UCC/사진',
             'date':datetime.date(2023,12,30),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82969'},
            {'title':'상명대학교',
             'content':'상명 계당학술 논문 공모전 신규 분야 : 논문/리포트',
             'date':datetime.date(2023,12,30),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82965'},
            {'title':'TH엔터테인먼트',
             'content':'Lets'' DIVE! 영상 공모전 분야 : 영상/UCC/사진',
             'date':datetime.date(2023, 12, 30),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82946'},
            {'title':'더마테스트',
             'content':'더마테스트 서포터즈 3기 모집 분야 : 대외활동/서포터즈',
             'date':datetime.date(2023, 12, 30),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82945'},
            {'title': '청소년그루터기재단',
             'content': '그루터기 학습멘토링 같이에듀 대학생 멘토 4기 모집 SPECIAL IDEA분야 : 광고/마케팅, 예체능/미술/음악, 대외활동/서포터즈, 봉사활동, 취업/창업, 기타',
             'date': datetime.date(2024,1,2),
             'link':'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82909'},
            {'title': '포스텍 소통과 공론 연구소',
             'content': '제4회 포스텍 SF 어워드 공모전 (제4회 POSTECH SF AWARD) SPECIAL IDEA분야 : 기획/아이디어, 광고/마케팅, 웹/모바일/IT, 과학/공학, 문학/글/시나리오',
             'date': datetime.date(2024, 1, 6),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82614'},
            {'title': '한국고등교육재단',
             'content': '한국고등교육재단 문우림 제3기 장학생 모집 분야 : 기타',
             'date': datetime.date(2024, 1, 11),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82933'},
            {'title': '숲속동화마을도서관',
             'content': '제12회 전국어린이 독후감쓰기 대회 분야 : 문학/글/시나리오',
             'date': datetime.date(2024, 1, 30),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82927'},
            {'title': '예술협회 아이테르',
             'content': '2024 예술협회 아이테르 범일가옥 전시공모 신규 분야 : 예체능/미술/음악',
             'date': datetime.date(2024, 2, 24),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=1&ix=82967'},
            {'title': '조아라',
             'content': '조아라 판무저격 웹소설 공모전 분야 : 문학/글/시나리오',
             'date': datetime.date(2024, 2, 28),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82944'},
            {'title': '비룡소',
             'content': '2024년 제5회 틴 스토리킹 분야 : 문학/글/시나리오',
             'date': datetime.date(2024, 3, 28),
             'link': 'https://www.wevity.com/?c=find&s=1&gbn=viewok&gp=2&ix=82950'}
    ]
    return data