# Generated by Django 4.2.5 on 2023-12-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.newuserinfo')),
            ],
            options={
                'db_table': 'deck',
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('vote', models.SmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.deck')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.newuserinfo')),
            ],
            options={
                'db_table': 'flashcard',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=4)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.newuserinfo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='uservote',
            constraint=models.UniqueConstraint(fields=('user', 'flashcard'), name='unique_user_flashcard_vote'),
        ),
    ]
