# Generated by Django 4.2.5 on 2023-10-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='vote',
            field=models.SmallIntegerField(default=0),
        ),
    ]
