# Generated by Django 4.2.5 on 2023-10-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_flashcard_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
