# Generated by Django 4.2.5 on 2023-10-24 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_flashcard_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['id']},
        ),
    ]
